/**
 * HackerNewsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const Item = require('./Item');

/**
 * Creates an instance of Ask
 */
class Ask extends Item {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.by = this.constructor.getValue(obj.by);
        this.descendants = this.constructor.getValue(obj.descendants);
        this.kids = this.constructor.getValue(obj.kids);
        this.score = this.constructor.getValue(obj.score);
        this.text = this.constructor.getValue(obj.text);
        this.time = this.constructor.getValue(obj.time);
        this.title = this.constructor.getValue(obj.title);
        this.type = this.constructor.getValue(obj.type);
        this.url = this.constructor.getValue(obj.url);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'by', realName: 'by' },
            { name: 'descendants', realName: 'descendants' },
            { name: 'kids', realName: 'kids', array: true },
            { name: 'score', realName: 'score' },
            { name: 'text', realName: 'text' },
            { name: 'time', realName: 'time' },
            { name: 'title', realName: 'title' },
            { name: 'type', realName: 'type', isDiscrim: true },
            { name: 'url', realName: 'url' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {
            ask: 'Ask',
        };
    }
}

module.exports = Ask;
