/**
 * HackerNewsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const Item = require('./Item');

/**
 * Creates an instance of PollOption
 */
class PollOption extends Item {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.by = this.constructor.getValue(obj.by);
        this.poll = this.constructor.getValue(obj.poll);
        this.score = this.constructor.getValue(obj.score);
        this.text = this.constructor.getValue(obj.text);
        this.time = this.constructor.getValue(obj.time);
        this.type = this.constructor.getValue(obj.type);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'by', realName: 'by' },
            { name: 'poll', realName: 'poll' },
            { name: 'score', realName: 'score' },
            { name: 'text', realName: 'text' },
            { name: 'time', realName: 'time' },
            { name: 'type', realName: 'type', isDiscrim: true },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {
            pollop: 'PollOption',
        };
    }
}

module.exports = PollOption;
