/**
 * HackerNewsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const Ask = require('../lib/Models/Ask');
const Story = require('../lib/Models/Story');
const Item = require('../lib/Models/Item');
const PollOption = require('../lib/Models/PollOption');
const Comment = require('../lib/Models/Comment');
const Job = require('../lib/Models/Job');
const Poll = require('../lib/Models/Poll');

const classMap = {
    Ask,
    Story,
    Item,
    PollOption,
    Comment,
    Job,
    Poll,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
